# idgen.toml

ver = "0.0.1"
#logPath = "/tmp/idgen.log"


[server]
addr = "0.0.0.0:14002"

[discovery]
serviceName = "idgen"
nodeID = "node1"
rPCAddr = "192.168.3.125:14002"
etcdAddrs = ["http://192.168.3.125:2379"]
interval = "2s"
tTL = "10s"

[etcd]
root = "/service/idgen/"
addrs = ["192.168.3.125:2379"]
timeout = "1s"

